let playersData = [
  {
    "username": "Barnard",
    "useremail": "bcoaster0@jigsy.com",
    "userpassword": "1234",
    "userage": "36",
    "userlocation": "North Vancouver"
  }, {
    "username": "Mathias",
    "useremail": "mstracey1@printfriendly.com",
    "userpassword": "1234",
    "userage": "36",
    "userlocation": "Maple Ridge"
  }, {
    "username": "Krishna",
    "useremail": "kstileman2@studiopress.com",
    "userpassword": "1234",
    "userage": "51",
    "userlocation": "Vancouver"
  }, {
    "username": "Shermie",
    "useremail": "sfolshom3@ftc.gov",
    "userpassword": "1234",
    "userage": "40",
    "userlocation": "Delta"
  }, {
    "username": "Gene",
    "useremail": "gapplebee4@hp.com",
    "userpassword": "1234",
    "userage": "21",
    "userlocation": "Richmond"
  }, {
    "username": "Dwight",
    "useremail": "dmckeand5@pbs.org",
    "userpassword": "1234",
    "userage": "51",
    "userlocation": "North Vancouver"
  }, {
    "username": "Miltie",
    "useremail": "mjedryka6@hhs.gov",
    "userpassword": "1234",
    "userage": "26",
    "userlocation": "Burnaby"
  }, {
    "username": "Francklin",
    "useremail": "fblockley7@google.de",
    "userpassword": "1234",
    "userage": "37",
    "userlocation": "Maple Ridge"
  }, {
    "username": "Ewen",
    "useremail": "elilly8@dailymotion.com",
    "userpassword": "1234",
    "userage": "44",
    "userlocation": "Maple Ridge"
  }, {
    "username": "Byron",
    "useremail": "bjina9@google.co.jp",
    "userpassword": "1234",
    "userage": "45",
    "userlocation": "New Westminster"
  }, {
    "username": "Boonie",
    "useremail": "bmettrickea@oakley.com",
    "userpassword": "1234",
    "userage": "51",
    "userlocation": "Delta"
  }, {
    "username": "Morie",
    "useremail": "mnorcopb@businessinsider.com",
    "userpassword": "1234",
    "userage": "23",
    "userlocation": "Maple Ridge"
  }, {
    "username": "Cesaro",
    "useremail": "chubbertc@globo.com",
    "userpassword": "1234",
    "userage": "58",
    "userlocation": "Coquitlam"
  }, {
    "username": "Ennis",
    "useremail": "eburnittd@unblog.fr",
    "userpassword": "1234",
    "userage": "37",
    "userlocation": "Burnaby"
  }, {
    "username": "Ferrel",
    "useremail": "fpomphrette@google.co.jp",
    "userpassword": "1234",
    "userage": "40",
    "userlocation": "Coquitlam"
  }, {
    "username": "Jesse",
    "useremail": "jdockseyf@ow.ly",
    "userpassword": "1234",
    "userage": "37",
    "userlocation": "Vancouver"
  }, {
    "username": "Engelbert",
    "useremail": "ebannong@linkedin.com",
    "userpassword": "1234",
    "userage": "41",
    "userlocation": "Burnaby"
  }, {
    "username": "Theo",
    "useremail": "tluckhursth@usgs.gov",
    "userpassword": "1234",
    "userage": "49",
    "userlocation": "Vancouver"
  }, {
    "username": "Em",
    "useremail": "espatai@dailymail.co.uk",
    "userpassword": "1234",
    "userage": "35",
    "userlocation": "West Vancouver"
  }, {
    "username": "Emilio",
    "useremail": "egringleyj@foxnews.com",
    "userpassword": "1234",
    "userage": "47",
    "userlocation": "Burnaby"
  }, {
    "username": "Lou",
    "useremail": "lmardeek@forbes.com",
    "userpassword": "1234",
    "userage": "29",
    "userlocation": "Richmond"
  }, {
    "username": "Natal",
    "useremail": "npotkinsl@slashdot.org",
    "userpassword": "1234",
    "userage": "29",
    "userlocation": "Langley"
  }, {
    "username": "Orrin",
    "useremail": "oautym@wikia.com",
    "userpassword": "1234",
    "userage": "53",
    "userlocation": "Burnaby"
  }, {
    "username": "Rich",
    "useremail": "rskirrown@uol.com.br",
    "userpassword": "1234",
    "userage": "39",
    "userlocation": "Langley"
  }, {
    "username": "Edd",
    "useremail": "etellwrighto@de.vu",
    "userpassword": "1234",
    "userage": "50",
    "userlocation": "West Vancouver"
  }, {
    "username": "Joseito",
    "useremail": "jwawerp@skyrock.com",
    "userpassword": "1234",
    "userage": "60",
    "userlocation": "New Westminster"
  }, {
    "username": "Aksel",
    "useremail": "adyshartq@ow.ly",
    "userpassword": "1234",
    "userage": "37",
    "userlocation": "North Vancouver"
  }, {
    "username": "Hagen",
    "useremail": "hwalklottr@fc2.com",
    "userpassword": "1234",
    "userage": "30",
    "userlocation": "Maple Ridge"
  }, {
    "username": "Frasier",
    "useremail": "fdodameads@skyrock.com",
    "userpassword": "1234",
    "userage": "21",
    "userlocation": "Richmond"
  }, {
    "username": "Olivier",
    "useremail": "oumbertt@patch.com",
    "userpassword": "1234",
    "userage": "31",
    "userlocation": "Langley"
  }, {
    "username": "Rudiger",
    "useremail": "rcollumbellu@flickr.com",
    "userpassword": "1234",
    "userage": "30",
    "userlocation": "Langley"
  }, {
    "username": "Abramo",
    "useremail": "aaltoftsv@nps.gov",
    "userpassword": "1234",
    "userage": "47",
    "userlocation": "Maple Ridge"
  }, {
    "username": "Noam",
    "useremail": "ncattloww@engadget.com",
    "userpassword": "1234",
    "userage": "28",
    "userlocation": "Port Moody"
  }, {
    "username": "Teddie",
    "useremail": "thuorticx@domainmarket.com",
    "userpassword": "1234",
    "userage": "26",
    "userlocation": "Port Moody"
  }, {
    "username": "Israel",
    "useremail": "inolleauy@ameblo.jp",
    "userpassword": "1234",
    "userage": "41",
    "userlocation": "Richmond"
  }, {
    "username": "Gonzalo",
    "useremail": "gradbandz@example.com",
    "userpassword": "1234",
    "userage": "35",
    "userlocation": "Langley"
  }, {
    "username": "Angelico",
    "useremail": "ascough10@weather.com",
    "userpassword": "1234",
    "userage": "51",
    "userlocation": "Coquitlam"
  }, {
    "username": "Basil",
    "useremail": "bhoulworth11@arstechnica.com",
    "userpassword": "1234",
    "userage": "54",
    "userlocation": "Langley"
  }, {
    "username": "Wallas",
    "useremail": "wkermode12@weibo.com",
    "userpassword": "1234",
    "userage": "29",
    "userlocation": "Langley"
  }, {
    "username": "Hamid",
    "useremail": "hmatzaitis13@typepad.com",
    "userpassword": "1234",
    "userage": "28",
    "userlocation": "Port Moody"
  }, {
    "username": "Olivero",
    "useremail": "opragnall14@sciencedirect.com",
    "userpassword": "1234",
    "userage": "51",
    "userlocation": "North Vancouver"
  }, {
    "username": "Domenico",
    "useremail": "ddaventry15@sbwire.com",
    "userpassword": "1234",
    "userage": "40",
    "userlocation": "New Westminster"
  }, {
    "username": "Niven",
    "useremail": "nsitwell16@illinois.edu",
    "userpassword": "1234",
    "userage": "38",
    "userlocation": "Port Moody"
  }, {
    "username": "Emmerich",
    "useremail": "ekiln17@bluehost.com",
    "userpassword": "1234",
    "userage": "35",
    "userlocation": "Maple Ridge"
  }, {
    "username": "Crichton",
    "useremail": "cfahy18@hud.gov",
    "userpassword": "1234",
    "userage": "27",
    "userlocation": "Coquitlam"
  }, {
    "username": "Doyle",
    "useremail": "dstanmore19@patch.com",
    "userpassword": "1234",
    "userage": "47",
    "userlocation": "West Vancouver"
  }, {
    "username": "Rafferty",
    "useremail": "rchappelle1a@japanpost.jp",
    "userpassword": "1234",
    "userage": "29",
    "userlocation": "Delta"
  }, {
    "username": "Darius",
    "useremail": "dlinebarger1b@miitbeian.gov.cn",
    "userpassword": "1234",
    "userage": "36",
    "userlocation": "Delta"
  }, {
    "username": "Tomas",
    "useremail": "tgreep1c@tiny.cc",
    "userpassword": "1234",
    "userage": "44",
    "userlocation": "Delta"
  }, {
    "username": "Tull",
    "useremail": "tspeedy1d@utexas.edu",
    "userpassword": "1234",
    "userage": "56",
    "userlocation": "Port Moody"
  }, {
    "username": "Artur",
    "useremail": "adorkins1e@opera.com",
    "userpassword": "1234",
    "userage": "40",
    "userlocation": "Vancouver"
  }, {
    "username": "Craggy",
    "useremail": "cminto1f@de.vu",
    "userpassword": "1234",
    "userage": "30",
    "userlocation": "Port Moody"
  }, {
    "username": "Briano",
    "useremail": "bcantopher1g@auda.org.au",
    "userpassword": "1234",
    "userage": "54",
    "userlocation": "Port Moody"
  }, {
    "username": "Baron",
    "useremail": "belstub1h@over-blog.com",
    "userpassword": "1234",
    "userage": "35",
    "userlocation": "Richmond"
  }, {
    "username": "Garrek",
    "useremail": "gandri1i@imgur.com",
    "userpassword": "1234",
    "userage": "30",
    "userlocation": "Langley"
  }, {
    "username": "Judon",
    "useremail": "jjarred1j@1688.com",
    "userpassword": "1234",
    "userage": "42",
    "userlocation": "Port Coquitlam"
  }, {
    "username": "Rik",
    "useremail": "rbeaby1k@nature.com",
    "userpassword": "1234",
    "userage": "28",
    "userlocation": "Burnaby"
  }, {
    "username": "Rhett",
    "useremail": "rkeyhoe1l@surveymonkey.com",
    "userpassword": "1234",
    "userage": "46",
    "userlocation": "Langley"
  }, {
    "username": "Hunt",
    "useremail": "hpalleske1m@redcross.org",
    "userpassword": "1234",
    "userage": "35",
    "userlocation": "Delta"
  }, {
    "username": "Casar",
    "useremail": "celderton1n@nsw.gov.au",
    "userpassword": "1234",
    "userage": "60",
    "userlocation": "Port Moody"
  }, {
    "username": "Kane",
    "useremail": "ksafhill1o@cam.ac.uk",
    "userpassword": "1234",
    "userage": "35",
    "userlocation": "West Vancouver"
  }, {
    "username": "Orrin",
    "useremail": "odanforth1p@weather.com",
    "userpassword": "1234",
    "userage": "48",
    "userlocation": "Richmond"
  }, {
    "username": "Winnie",
    "useremail": "wgunderson1q@google.com",
    "userpassword": "1234",
    "userage": "24",
    "userlocation": "Port Coquitlam"
  }, {
    "username": "Jeromy",
    "useremail": "jpirnie1r@elegantthemes.com",
    "userpassword": "1234",
    "userage": "36",
    "userlocation": "Richmond"
  }, {
    "username": "Brandon",
    "useremail": "bcordeix1s@ebay.co.uk",
    "userpassword": "1234",
    "userage": "36",
    "userlocation": "Port Coquitlam"
  }, {
    "username": "Tadio",
    "useremail": "tpyvis1t@istockphoto.com",
    "userpassword": "1234",
    "userage": "35",
    "userlocation": "West Vancouver"
  }, {
    "username": "Oates",
    "useremail": "oramel1u@nature.com",
    "userpassword": "1234",
    "userage": "57",
    "userlocation": "Port Moody"
  }, {
    "username": "Lucius",
    "useremail": "lpeidro1v@unicef.org",
    "userpassword": "1234",
    "userage": "53",
    "userlocation": "Langley"
  }, {
    "username": "Garrik",
    "useremail": "ggreenstreet1w@miitbeian.gov.cn",
    "userpassword": "1234",
    "userage": "41",
    "userlocation": "Vancouver"
  }, {
    "username": "Thorpe",
    "useremail": "tsimonetti1x@msu.edu",
    "userpassword": "1234",
    "userage": "23",
    "userlocation": "Burnaby"
  }, {
    "username": "Schuyler",
    "useremail": "sgandy1y@cbsnews.com",
    "userpassword": "1234",
    "userage": "44",
    "userlocation": "Langley"
  }, {
    "username": "Sherwynd",
    "useremail": "ssappson1z@unc.edu",
    "userpassword": "1234",
    "userage": "46",
    "userlocation": "Delta"
  }, {
    "username": "Denys",
    "useremail": "dsemrad20@epa.gov",
    "userpassword": "1234",
    "userage": "60",
    "userlocation": "Delta"
  }, {
    "username": "Huey",
    "useremail": "hmicah21@google.ca",
    "userpassword": "1234",
    "userage": "26",
    "userlocation": "Port Moody"
  }, {
    "username": "Ash",
    "useremail": "aboman22@ifeng.com",
    "userpassword": "1234",
    "userage": "35",
    "userlocation": "Coquitlam"
  }, {
    "username": "Lynn",
    "useremail": "lcammis23@marriott.com",
    "userpassword": "1234",
    "userage": "40",
    "userlocation": "Delta"
  }, {
    "username": "Sigfrid",
    "useremail": "spautot24@hibu.com",
    "userpassword": "1234",
    "userage": "41",
    "userlocation": "West Vancouver"
  }, {
    "username": "Micky",
    "useremail": "mmccutheon25@g.co",
    "userpassword": "1234",
    "userage": "33",
    "userlocation": "Vancouver"
  }, {
    "username": "Towny",
    "useremail": "thischke26@com.com",
    "userpassword": "1234",
    "userage": "23",
    "userlocation": "West Vancouver"
  }, {
    "username": "Tyler",
    "useremail": "tpennings27@php.net",
    "userpassword": "1234",
    "userage": "48",
    "userlocation": "Richmond"
  }, {
    "username": "Jose",
    "useremail": "jcradock28@miibeian.gov.cn",
    "userpassword": "1234",
    "userage": "47",
    "userlocation": "Port Moody"
  }, {
    "username": "Krispin",
    "useremail": "ksimmgen29@eepurl.com",
    "userpassword": "1234",
    "userage": "32",
    "userlocation": "Port Coquitlam"
  }, {
    "username": "Stanley",
    "useremail": "sallder2a@gmpg.org",
    "userpassword": "1234",
    "userage": "27",
    "userlocation": "Coquitlam"
  }, {
    "username": "Hamlin",
    "useremail": "handrzej2b@blogger.com",
    "userpassword": "1234",
    "userage": "57",
    "userlocation": "North Vancouver"
  }, {
    "username": "Martyn",
    "useremail": "mmacclay2c@slashdot.org",
    "userpassword": "1234",
    "userage": "20",
    "userlocation": "New Westminster"
  }, {
    "username": "Seward",
    "useremail": "sfraschetti2d@va.gov",
    "userpassword": "1234",
    "userage": "21",
    "userlocation": "Port Coquitlam"
  }, {
    "username": "Shermie",
    "useremail": "sambroix2e@ning.com",
    "userpassword": "1234",
    "userage": "43",
    "userlocation": "Coquitlam"
  }, {
    "username": "Gage",
    "useremail": "ghendriksen2f@reddit.com",
    "userpassword": "1234",
    "userage": "23",
    "userlocation": "Richmond"
  }, {
    "username": "Udale",
    "useremail": "ukersey2g@dagondesign.com",
    "userpassword": "1234",
    "userage": "49",
    "userlocation": "Richmond"
  }, {
    "username": "Jefferey",
    "useremail": "jlemarchant2h@wufoo.com",
    "userpassword": "1234",
    "userage": "24",
    "userlocation": "North Vancouver"
  }, {
    "username": "Brant",
    "useremail": "bfilipowicz2i@go.com",
    "userpassword": "1234",
    "userage": "49",
    "userlocation": "Port Moody"
  }, {
    "username": "Jaymie",
    "useremail": "jhoulden2j@cam.ac.uk",
    "userpassword": "1234",
    "userage": "41",
    "userlocation": "Port Moody"
  }, {
    "username": "Nevil",
    "useremail": "nmcnirlan2k@ameblo.jp",
    "userpassword": "1234",
    "userage": "46",
    "userlocation": "North Vancouver"
  }, {
    "username": "Riley",
    "useremail": "rspata2l@desdev.cn",
    "userpassword": "1234",
    "userage": "46",
    "userlocation": "Richmond"
  }, {
    "username": "Lazaro",
    "useremail": "lkalvin2m@github.com",
    "userpassword": "1234",
    "userage": "40",
    "userlocation": "Richmond"
  }, {
    "username": "Bron",
    "useremail": "bchawner2n@comsenz.com",
    "userpassword": "1234",
    "userage": "31",
    "userlocation": "Delta"
  }, {
    "username": "Gustave",
    "useremail": "geastope2o@yellowbook.com",
    "userpassword": "1234",
    "userage": "39",
    "userlocation": "Richmond"
  }, {
    "username": "Barnabe",
    "useremail": "bcoathup2p@yandex.ru",
    "userpassword": "1234",
    "userage": "48",
    "userlocation": "Burnaby"
  }, {
    "username": "Inigo",
    "useremail": "imullett2q@mashable.com",
    "userpassword": "1234",
    "userage": "24",
    "userlocation": "Vancouver"
  }, {
    "username": "Cory",
    "useremail": "cchoke2r@booking.com",
    "userpassword": "1234",
    "userage": "41",
    "userlocation": "Richmond"
  }];
  